services:
  next-app:
    container_name: next-app-production

    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      # args:
      #   ENV_VARIABLE: ${ENV_VARIABLE}

    restart: always

    ports:
      - 4000:4000

    networks:
      - my_network

  mongodb:
      container_name: mongodb-production

      image: mongo

      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-s3c0r3p4$$}
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-next-app}
        - MONGO_USERNAME=${MONGO_USERNAME:-user}
        - MONGO_PASSWORD=${MONGO_PASSWORD:-4n0th3rp4$$}

      restart: always

      volumes:
        - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

      ports:
        - 27017:27017

      networks:
        - my_network

networks:
  my_network:
    driver: bridge
