services:
  next-app:
    container_name: next-app-development

    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # environment:
    # -- ENV_VARIABLE: ${ENV_VARIABLE}

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public

    ports:
      - 3000:3000

    networks:
      - my_network

  mongodb:
      container_name: mongodb-development

      image: mongo

      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-s3c0r3p4$$}
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-next-app}

      ports:
        - 27017:27017

      networks:
        - my_network

networks:
  my_network:
    driver: bridge
