services:
  next-app:
    container_name: next-app

    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # environment:
    # -- ENV_VARIABLE: ${ENV_VARIABLE}

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public

    ports:
      - 3000:3000

    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

networks:
  my_network:
    driver: bridge
